name: Bot Pinger 24/7

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping
        env:
          # GitHub автоматически подставит ссылку из твоих секретов настроек
          BOT_URL: ${{ secrets.RENDER_URL }}
        run: |
          curl -s "$BOT_URL"
          echo "ping"
