name: Bot Pinger 24/7

on:
  schedule:
    # Запуск каждые 5 минут круглые сутки
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping
        run: |
          # Вставь сюда свою ссылку на бота из панели Render
          curl -s https://onrender.com
          echo "ping"
